// <auto-generated />
using System;
using System.Collections.Generic;
using GymCRM.MembershipAPI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymCRM.MembershipAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymCRM.MembershipAPI.Infrastructure.Entities.Account", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("HashSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.HasKey("Guid");

                    b.HasIndex(new[] { "Email" }, "IX_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Guid" }, "IX_Guid")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Guid = new Guid("c1c826ab-5195-44a6-b3ce-b236b54daf78"),
                            DateCreated = new DateTime(2025, 4, 7, 17, 11, 46, 865, DateTimeKind.Utc).AddTicks(3453),
                            Email = "test@test.com",
                            HashSalt = "E84A81CE8413C73A3B7D96ECD",
                            HashedPassword = "9NMsR7hdMEjiE6wxjn69DgAVnER/5QUGHU8czqtEuK0=",
                            Id = 1
                        });
                });

            modelBuilder.Entity("GymCRM.MembershipAPI.Infrastructure.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AccountGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<int>("GymSubscriptionType")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("PersonalTrainerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("WorkingExperienceInMonths")
                        .HasColumnType("integer");

                    b.Property<List<Guid>>("WorkoutGroupIds")
                        .HasColumnType("uuid[]");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AccountGuid" }, "IX_AccountGuid")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "IX_Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Email1");

                    b.ToTable("Members", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountGuid = new Guid("c1c826ab-5195-44a6-b3ce-b236b54daf78"),
                            AccountType = 1,
                            Email = "test@test.com",
                            Gender = 1,
                            GymSubscriptionType = 1
                        });
                });

            modelBuilder.Entity("GymCRM.MembershipAPI.Infrastructure.Entities.Member", b =>
                {
                    b.HasOne("GymCRM.MembershipAPI.Infrastructure.Entities.Account", "Account")
                        .WithOne("Member")
                        .HasForeignKey("GymCRM.MembershipAPI.Infrastructure.Entities.Member", "AccountGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Account_Members");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("GymCRM.MembershipAPI.Infrastructure.Entities.Account", b =>
                {
                    b.Navigation("Member")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
