// <auto-generated />
using System;
using GymCRM.UsersAPI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymCRM.UsersAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240928162013_AddUsersToDB")]
    partial class AddUsersToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymCRM.UsersAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("text");

                    b.Property<int?>("PersonalTrainerId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.Property<int?>("WorkoutGroupId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GymUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateJoined = new DateTime(2024, 9, 27, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "test@test.com",
                            FirstName = "Admin",
                            LastName = "Adminski",
                            PhoneNumber = "123456789",
                            UserType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
